version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      # Ensure node_modules inside the container is not overwritten
      - /app/node_modules
    command: npm start